const express = require("express")
const updateUserProfile = require("../controller/userPorfile/updateUserProfile.controller")
const updateUserProfileDocument = require("../controller/userPorfile/updateUserProfileDocument.controller")
const deleteUserProfileDocument = require("../controller/userPorfile/deleteUserProfileDocument.controller")
const getUserProfileDocument = require("../controller/userPorfile/getUserProfileDocument.controller")
const downloadUserProfileDocument = require("../controller/userPorfile/downloadUserProfileDocument.controller")
const displayValidDocument = require("../controller/userPorfile/displayValidDocument.controller")
const displayProfilePermission = require("../controller/userPorfile/displayProfilePermission.controller")
const displayAttendace = require("../controller/userPorfile/displayAttendance.controller")
const displayHolidayUserProfile = require("../controller/userPorfile/displayHolidatUserProfile.controller")
const applyForLeaveUserProfile = require("../controller/userPorfile/applyForLeaveUserProfile.controller")
const userProfileEditLeave = require("../controller/userPorfile/userProfileEditLeave.controller")
const deleteLeaveApplication = require("../controller/userPorfile/deleteLeaveApplication.controller")
const getAllLeaveApplicationUserProfile = require("../controller/userPorfile/getAllLeaveApplicationUserProfile.controller")


const router = express.Router()

router.put("/update", updateUserProfile)
router.patch("/updateDocument", updateUserProfileDocument)
router.delete("/deleteDocument/:clientId/:userId/", deleteUserProfileDocument)
router.get("/getDocument/:clientId/:userId", getUserProfileDocument)
router.get("/downloadDocument/:clientId/:userId", downloadUserProfileDocument)
router.get("/displayDocuments/:clientId/:userId", displayValidDocument)
router.get("/displayPermission/:clientId/:userId", displayProfilePermission)
router.get("/displayAttendance/:clientId/:userId", displayAttendace)
router.get("/displayHoliday/:clientId/:userId", displayHolidayUserProfile)
router.post("/applyLeave/", applyForLeaveUserProfile)
router.patch("/editLeave", userProfileEditLeave)
router.delete("/deleteLeave/:clientId/:userId", deleteLeaveApplication)
router.get("/getAllLeave/:clientId/:userId", getAllLeaveApplicationUserProfile)

module.exports = router