const getAllEmployee = async (page= 1, perPage = 10, searchKey= "", clientId) =>{
    try {
        return {status: true, message: "Fetched all data of employee", data:{
            "data": [
              {
                "firstName": "Alice",
                "lastName": "Smith",
                "companyId": "23456bcdef",
                "designationId": "78901ghijk",
                "joiningDate": "2021-11-03",
                "roleId": "manager456",
                "documentId": "78b9861a31234cabc089ecb12",
                "email": "alice.smith@example.com",
                "phone": "+1987654321",
                "gender": "Female",
                "age": 28,
                "bloodGroup": "A+",
                "city": "Los Angeles",
                "state": "California",
                "country": "USA",
                "ZipCode": "90001",
                "address": "5678 Maple Avenue, Apt 202",
                "isVerified": true,
                "isActive": true,
                "createdAt": "2021-11-03T10:15:30Z",
                "updatedAt": "2023-01-10T14:45:20Z"
              },
              {
                "firstName": "Johnnn",
                "lastName": "Doe",
                "companyId": "12345abcde",
                "designationId": "67890fghij",
                "joiningDate": "2022-01-15",
                "roleId": "admin123",
                "documentId": "67b9859a31301b22209ecb68",
                "email": "john.doe@example.com",
                "phone": "+1234567890",
                "gender": "Male",
                "age": 30,
                "bloodGroup": "O+",
                "city": "New York",
                "state": "New York",
                "country": "USA",
                "ZipCode": "10001",
                "address": "1234 Elm Street, Apt 101",
                "isVerified": true,
                "isActive": true,
                "createdAt": "2021-11-03T10:15:30Z",
                "updatedAt": "2023-01-10T14:45:20Z"
              },
              {
                "firstName": "Michael",
                "lastName": "Johnson",
                "companyId": "34567cdefg",
                "designationId": "89012ijklm",
                "joiningDate": "2020-05-19",
                "roleId": "developer789",
                "documentId": "89c9872b41325dabf08fccd23",
                "email": "michael.johnson@example.com",
                "phone": "+1098765432",
                "gender": "Male",
                "age": 32,
                "bloodGroup": "B+",
                "city": "San Francisco",
                "state": "California",
                "country": "USA",
                "ZipCode": "94102",
                "address": "9101 Pine Street, Suite 403",
                "isVerified": true,
                "isActive": false,
                "createdAt": "2020-05-19T09:30:10Z",
                "updatedAt": "2024-02-14T16:20:00Z"
              },
              {
                "firstName": "Emma",
                "lastName": "Williams",
                "companyId": "45678defgh",
                "designationId": "90123klmno",
                "joiningDate": "2019-07-22",
                "roleId": "designer012",
                "documentId": "90d9843c52436cabd09bcd48",
                "email": "emma.williams@example.com",
                "phone": "+1122334455",
                "gender": "Female",
                "age": 26,
                "bloodGroup": "AB+",
                "city": "Chicago",
                "state": "Illinois",
                "country": "USA",
                "ZipCode": "60601",
                "address": "1234 Oak Boulevard, Apt 504",
                "isVerified": true,
                "isActive": true,
                "createdAt": "2019-07-22T12:45:50Z",
                "updatedAt": "2023-12-30T11:30:40Z"
              },
              {
                "firstName": "David",
                "lastName": "Brown",
                "companyId": "56789efghi",
                "designationId": "01234mnopq",
                "joiningDate": "2023-03-10",
                "roleId": "administrator345",
                "documentId": "12e9837f63529dabf20ecd56",
                "email": "david.brown@example.com",
                "phone": "+1223344556",
                "gender": "Male",
                "age": 35,
                "bloodGroup": "O-",
                "city": "Miami",
                "state": "Florida",
                "country": "USA",
                "ZipCode": "33101",
                "address": "3456 Pinecrest Road, Unit 6",
                "isVerified": false,
                "isActive": true,
                "createdAt": "2023-03-10T15:20:00Z",
                "updatedAt": "2025-02-26T08:10:15Z"
              },
              {
                "firstName": "Sophia",
                "lastName": "Davis",
                "companyId": "67890fghij",
                "designationId": "12345qrstuv",
                "joiningDate": "2022-08-05",
                "roleId": "lead analyst678",
                "documentId": "34f9827b73615cdad11cfa78",
                "email": "sophia.davis@example.com",
                "phone": "+1012345678",
                "gender": "Female",
                "age": 29,
                "bloodGroup": "AB-",
                "city": "Austin",
                "state": "Texas",
                "country": "USA",
                "ZipCode": "73301",
                "address": "5678 Cedar Drive, Apt 303",
                "isVerified": true,
                "isActive": true,
                "createdAt": "2022-08-05T10:35:10Z",
                "updatedAt": "2023-11-21T17:50:05Z"
              }
            ],
            "metaData": {
              "currentPage": 1,
              "perPage": 10,
              "searchKey": "",
              "totalData": 5,
              "totalPages": 1
            }
          }
          }
    } catch (error) {
        
    }
}
module.exports = getAllEmployee